// Generated by CoffeeScript 1.10.0

/**
 * Главный скрипт приложения
 * @author Pavel Tretyakov 1@tretyakovpavel.ru
 */
define(function(require) {
  'use strict';
  var ContentView, Marionette, app;
  require('bootstrap');
  Marionette = require('marionette');
  ContentView = require('views/content');
  app = new Marionette.Application({
    debug: true,
    regions: {
      regionContainer: '#content'
    },
    initialize: function() {
      if (this.debug) {
        return console.log('Initialize marionette application');
      }
    },
    preload: function() {
      if (this.debug) {
        console.log('Completing preload function');
      }
      return this.regionContainer.show(new ContentView());
    }
  });
  app.addInitializer(function(options) {
    return this.preload();
  });
  Marionette.Renderer.render = function(template, data) {
    return _.template(template)(data);
  };
  return app;
});
