// Generated by CoffeeScript 1.10.0
define(function(require) {
  'use strict';
  var LayoutTemplate, Marionette, PostsView;
  Marionette = require('marionette');
  LayoutTemplate = require('text!tmpls/content.tpl');
  PostsView = require('views/posts');
  return Marionette.LayoutView.extend({
    debug: true,
    template: LayoutTemplate,
    ui: {
      'buttonShowPosts': '.show-posts'
    },
    events: {
      'click @ui.buttonShowPosts': 'showPosts'
    },
    regions: {
      regionPosts: '#region-posts'
    },
    initialize: function() {
      if (this.debug) {
        console.log('Initialize content Layout');
      }
      return this.on('render', this.afterRender, this);
    },
    afterRender: function() {
      this.regionPosts.show(new PostsView());
      return $('#content').carousel({
        interval: false
      });
    },
    showPosts: function(e) {
      if (this.debug) {
        console.log('Show posts button');
      }
      return $('#content').carousel('prev');
    }
  });
});
