// Generated by CoffeeScript 1.10.0
define(function(require) {
  'use strict';
  var LayoutTemplate, Marionette, PostsView;
  Marionette = require('marionette');
  LayoutTemplate = require('text!tmpls/content.tpl');
  PostsView = require('views/posts');
  return Marionette.LayoutView.extend({
    debug: true,
    template: LayoutTemplate,
    ui: {
      'buttonShowPosts': '.show-posts'
    },
    events: {
      'click @ui.buttonShowPosts': 'showPosts'
    },
    regions: {
      regionPosts: '#region-posts'
    },
    initialize: function() {
      if (this.debug) {
        console.log('Initialize content Layout');
      }
      return this.on('render', this.afterRender, this);
    },
    afterRender: function() {
      this.postsView = new PostsView();
      this.regionPosts.show(this.postsView);
      $('#content').carousel({
        interval: false
      });
      return $('body').on('keyup', '#search-input', (function(_this) {
        return function() {
          return _this.changedInput();
        };
      })(this));
    },
    showPosts: function(e) {
      if (this.debug) {
        console.log('Show posts button');
      }
      return $('#content').carousel('prev');
    },
    changedInput: function() {
      if (this.debug) {
        console.log('Новый поисковый запрос', $('#search-input').val());
      }
      return this.postsView.model.set('query', $('#search-input').val());
    }
  });
});
