// Generated by CoffeeScript 1.10.0
define(function(require) {
  'use strict';
  var ContentModel, LayoutTemplate, Marionette, PostsView, TextView;
  Marionette = require('marionette');
  LayoutTemplate = require('text!tmpls/content.tpl');
  PostsView = require('views/posts');
  ContentModel = Backbone.Model.extend();
  TextView = Marionette.ItemView.extend({
    template: 'text view template'
  });
  return Marionette.LayoutView.extend({
    debug: true,
    template: LayoutTemplate,
    regions: {
      regionText: '#region-text',
      regionPosts: '#region-posts'
    },
    initialize: function() {
      if (this.debug) {
        console.log('Initialize content Layout');
      }
      this.model = new ContentModel();
      this.model.set('test', 'Google test');
      return this.on('render', this.afterRender, this);
    },
    afterRender: function() {
      this.regionText.show(new TextView());
      return this.regionPosts.show(new PostsView());
    }
  });
});
