// Generated by CoffeeScript 1.10.0
define(function(require) {
  'use strict';
  var Collection, ItemView, Marionette, PostsCollectionView, TemplateItem;
  Marionette = require('marionette');
  TemplateItem = require('text!tmpls/post_item.tpl');
  Collection = Backbone.Collection.extend();
  ItemView = Marionette.ItemView.extend({
    template: TemplateItem
  });
  PostsCollectionView = Marionette.CollectionView.extend({
    debug: true,
    childView: ItemView,
    initialize: function() {
      if (this.debug) {
        console.log('Init posts collection view');
      }
      $.ajax({
        url: 'https://ajax.googleapis.com/ajax/services/search/news?v=1.0&q=путин',
        dataType: 'jsonp'
      }).done((function(_this) {
        return function(data) {
          if (_this.debug) {
            console.log('Data loaded', data.responseData.results);
          }
          return _this.collection.reset(data.responseData.results);
        };
      })(this));
      return this.collection = new Collection();
    }
  });
  return PostsCollectionView;
});
