// Generated by CoffeeScript 1.10.0
define(function(require) {
  'use strict';
  var Marionette, PostsCollectionView;
  Marionette = require('marionette');
  PostsCollectionView = Marionette.CollectionView.extend({
    debug: true,
    initialize: function() {
      if (this.debug) {
        return console.log('Init posts collection view');
      }
    }
  });
  return PostsCollectionView;
});
