// Generated by CoffeeScript 1.10.0
define(function(require) {
  'use strict';
  var Collection, ItemView, Marionette, Model, NoResultTpl, PostTemplate, PostsCollectionView, TemplateItem;
  Marionette = require('marionette');
  TemplateItem = require('text!tmpls/post_item.tpl');
  PostTemplate = require('text!tmpls/post_content.tpl');
  NoResultTpl = require('text!tmpls/no_search_result.tpl');
  Collection = Backbone.Collection.extend();
  Model = Backbone.Model.extend({
    defaults: {
      query: 'путин'
    }
  });
  ItemView = Marionette.ItemView.extend({
    template: TemplateItem,
    ui: {
      'linksShowPost': '.show-post-content'
    },
    events: {
      'click @ui.linksShowPost': 'showPostContent'
    },
    showPostContent: function(e) {
      $('#region-text').html(_.template(PostTemplate)(this.model.toJSON()));
      $('#content').carousel('next');
      return e.preventDefault();
    }
  });
  PostsCollectionView = Marionette.CollectionView.extend({
    debug: true,
    childView: ItemView,
    initialize: function() {
      if (this.debug) {
        console.log('Init posts collection view');
      }
      this.model = new Model();
      this.collection = new Collection();
      this.model.on('change:query', this.fetchData, this);
      this.on('render', this.afterRender, this);
      return this.fetchData();
    },
    afterRender: function() {
      return $(document).ajaxStart((function(_this) {
        return function() {
          return _this.$el.html('<div class="loader">Loading...</div>');
        };
      })(this));
    },
    fetchData: function() {
      var no_image_url;
      no_image_url = 'http://theslogsweep.com/wp-content/themes/mightymag/images/no_thumb.png';
      if (!this.model.get('query')) {
        return this.model.set('query', '');
      } else {
        return $.ajax({
          url: 'https://ajax.googleapis.com/ajax/services/search/news',
          data: {
            v: '1.0',
            rsz: 8,
            q: this.model.get('query')
          },
          dataType: 'jsonp'
        }).done((function(_this) {
          return function(data) {
            var Results, i, len, post;
            Results = data.responseData.results;
            if (_this.debug) {
              console.log('Data loaded', Results);
            }
            for (i = 0, len = Results.length; i < len; i++) {
              post = Results[i];
              if (!post.image) {
                post.image = {};
                post.image.url = no_image_url;
              }
            }
            $('.loader').remove();
            if (Results.length === 0) {
              console.error(_this.$el.html(NoResultTpl));
            }
            return _this.collection.reset(data.responseData.results);
          };
        })(this));
      }
    }
  });
  return PostsCollectionView;
});
